
import tkinter
from tkinter import *
root = Tk()
root.title("My Custom GUI")
root.geometry("300x500")
root.configure(bg="#f7f7f7") 
btn = Button(root, text="Click Me", fg="white", bg="#d6336c")
btn.pack(pady=8)
lbl = Label(root, text="This is a label", bg="#ffeb99")
lbl.pack(pady=8)
entry_box = Entry(root, width=20)
entry_box.pack(pady=8)
txt_box = Text(root, width=20, height=10)
txt_box.pack(pady=8)
option_var = StringVar()
radio1 = Radiobutton(root, text="Option A", variable=option_var, value="A")
radio1.pack()
radio2 = Radiobutton(root, text="Option B", variable=option_var, value="B")
radio2.pack()
check = Checkbutton(root, text="I Agree")
check.pack(pady=8)
lst = Listbox(root)
lst.pack(pady=8)
lst.insert(1, "First")
lst.insert(2, "Second")
lst.insert(3, "Third")
lst.config(font=("Consolas", 12))
root.mainloop()